Initial recipe
open-ce/nlohmann_json-feedstock pull request #1
Opened 2021-07-07 14:14 UTC by npanpaliya

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/main/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/main/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/main/tests/) to validate this change?  

## Description

Initial recipe for nlohmann_json. I've forked it from conda-forge and updated it as per Open-CE

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/main/MAINTAINERS.md) requests changes, they must be addressed.

2021-07-07 14:30 UTC, bnemanich approved these changes

2021-07-07 14:31 UTC, bnemanich requested changes
This is missing the CI files and README.

2021-07-26 15:49 UTC, bnemanich approved these changes

2021-07-26 16:17 UTC, jayfurmanek approved these changes

2021-07-27 13:34 UTC, merged